image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup workspace
    init: ./build.sh
    command: |
      ln -s /home/gitpod/.ansible/ /workspace/cloud-janitor-collection/.ansible
      ln -s /tmp /workspace/cloud-janitor-collection/.tmp
      echo "Workspace command setup at $(date)"

ports:
  - port: 40000-50000
    onOpen: ignore

vscode:
  extensions:
    - redhat.ansible
