image:
  file: .gitpod.Dockerfile

tasks:
  - name: Pre-build workspace
    command: echo "Workspace test command at $(date)"
    init: ansible-galaxy collection build
    
ports:
  - port: 40000-50000
    onOpen: ignore

vscode:
  extensions:
    - redhat.ansible
