name: Test Version

on:
  workflow_call:
    inputs:
      ocp-version:
        type: string
      opct-version:
        type: string

jobs:
  test_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test version
      run: |
        echo "Testing version ${ocp-version}-${opct-version}..."
        # Add your commands to test the version here
