name: Test one version

on:
  workflow_dispatch:
    inputs:
      ocp-version:
        description: 'The OpenShift Container Platform version to use'
        required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run heavy build
        run: |
          echo "Run ocp-version ${{ inputs.ocp-version }}, opct-version ${{ inputs.opct-version }}"
          sleep 3

