name: Test all versions 

on:
  workflow_dispatch: {}

jobs:
  iterate_and_call:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocp-version: ['4.12', '4.11', '4.10']
        opct-version: ['0.3', '0.2', '0.0']
    steps:
      - name: Iterate over Compatibility Matrix
        run: |
          echo "ocp-version: ${{ matrix.ocp-version }}, opct-version: ${{ matrix.opct-version }}"

