name: Test all versions 

on:
  workflow_dispatch: {}

jobs:
  iterate_and_call:
    strategy:
      matrix:
        ocp-version: ['4.12', '4.11', '4.10']
        opct-version: ['0.3', '0.2', '0.0']
    
    uses: CaravanaCloud/cloud-janitor-collection/.github/workflows/test-version.yml@main
    if: |
          (matrix.ocp-version == '4.12') && (matrix.opct-version == '0.3')
          || (matrix.ocp-version == '4.12') && (matrix.opct-version == '0.2')
          || (matrix.ocp-version == '4.11') && (matrix.opct-version == '0.2')
    with:
          ocp-version: ${{ matrix.ocp-version }}
          opct-version: ${{ matrix.opct-version }}

