name: Test single version set

on:
  workflow_dispatch:
    inputs:
      a-version:
        description: a version
      b-version:
        description: b version

jobs:
  test_version:
    runs-on: ubuntu-latest
    steps:
    - name: Test version
      run: |
        echo "Testing version ${{ github.event.inputs.a-version }} - ${{ github.event.inputs.b-version }}..."
