name: Test single version

on:
  workflow_dispatch:
    inputs:
      ocp-version:
        description: ocp version
      opct-version:
        description: opct version

jobs:
  test_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test version
      run: |
        echo "Testing version ${ocp-version}-${opct-version}..."
        # Add your commands to test the version here
