name: Test all versions 

on:
  workflow_dispatch: {}

jobs:
  iterate_and_call:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a-version: ['1.0', '2.0', '3.0']
        b-version: ['A.B', 'C.D', 'E.F']
    steps:
      - name: Iterate over Compatibility Matrix
        if: |
          (matrix.a-version == '1.0') && (matrix.b-version == 'A.B')
          || (matrix.a-version == '1.0') && (matrix.b-version == 'C.D')
          || (matrix.a-version == '2.0') 
        uses: CaravanaCloud/cloud-janitor-collection/.github/workflows/test-version.yml@main
        with:
          a-version: ${{ matrix.a-version }}
          b-version: ${{ matrix.b-version }}
