name: Test all versions

on:
  workflow_dispatch:
    inputs:
      ocp-versions:
        description: 'A list of versions to iterate over'
        required: false
        default: '["4.12", "4.11", "4.10"]'
      opct-versions:
        description: 'A map of versions to iterate over'
        required: false
        default: '{"4.12": ["0.3", "0.2"], "4.11": ["0.2"], "4.10": ["0.0"]}'

jobs:
  iterate_and_call:
    runs-on: ubuntu-latest
    steps:
      - name: Iterate over Compatibility Matrix
        run: |
          for ocp-version in ${{ fromJson(inputs.ocp-versions) }}; do
            for opct-version in ${{ fromJson(inputs.opct-versions)[ocp-version] }}; do
              echo "Building ocp-version $ocp-version, opct-version $opct-version"
              # call another GitHub action with version and build as inputs
            done
          done
